---
- name: Настройка пользователя brickdev
  hosts: all
  become: yes
  tasks:
    - name: Создание нового пользователя brickdev
      user:
        name: brickdev
        password: "{{ 'pass' | password_hash('sha512') }}"
        state: present

    - name: Разрешение авторизации по ключу
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
      notify: restart ssh

    - name: Запрещение логина по SSH от пользователя root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: restart ssh

    - name: Копирование публичного ключа для пользователя brickdev
      authorized_key:
        user: brickdev
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb"

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
