version: '3.8'

services:
  app:
    build: .
    deploy:
      replicas: 3
    environment:
      - UUID=${HOSTNAME}
    ports:
      - "3000"
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
